<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RestoreGeneralConcreteMixSeeder extends Seeder
{
    public function run(): void
    {
        $rows = [
            [
                'id' => 5,
                'company_code' => 'general',
                'costPrice' => 0.00,
                'salePrice' => 0.00,
                'branch_id' => null,
                'classification' => 'C25',
                'cement' => 0.00,
                'sand' => 0.00,
                'gravel' => 0.00,
                'water' => 0.00,
                'cement_code' => null,
                'sand_code' => null,
                'gravel_code' => null,
                'water_code' => null,
                'notes' => 'النوع: كونكريت عادي, الاستخدام: أساسات، أعمدة، جدران، بلاطات عامة, الملاحظات: الأكثر شيوعاً — w/c بين 0.45-0.55، يحتاج معالجة 7 أيام على الأقل, البيئة المناسبة: بيئات عادية بدون أملاح',
                'created_at' => '2026-04-13 14:11:59',
                'updated_at' => '2026-04-13 14:16:34',
            ],
            [
                'id' => 6,
                'company_code' => 'general',
                'costPrice' => 0.00,
                'salePrice' => 0.00,
                'branch_id' => null,
                'classification' => 'C60',
                'cement' => 0.00,
                'sand' => 0.00,
                'gravel' => 0.00,
                'water' => 0.00,
                'cement_code' => null,
                'sand_code' => null,
                'gravel_code' => null,
                'water_code' => null,
                'notes' => 'النوع: عالي المقاومة, الاستخدام: أبراج، جسور، أعمدة رئيسية، منشآت ثقيلة, الملاحظات: يحتوي سيليكا فيوم وملدنات فائقة — w/c أقل من 0.35 — يستلزم نقلاً وصباً دقيقاً, البيئة المناسبة: مشاريع ضخمة وثقيلة التحميل',
                'created_at' => '2026-04-13 14:11:59',
                'updated_at' => '2026-04-13 14:16:34',
            ],
            [
                'id' => 7,
                'company_code' => 'general',
                'costPrice' => 0.00,
                'salePrice' => 0.00,
                'branch_id' => null,
                'classification' => 'C30',
                'cement' => 0.00,
                'sand' => 0.00,
                'gravel' => 0.00,
                'water' => 0.00,
                'cement_code' => null,
                'sand_code' => null,
                'gravel_code' => null,
                'water_code' => null,
                'notes' => 'النوع: مقاوم للكبريتات, الاستخدام: أساسات في تربة مالحة، صرف صحي، مناطق ساحلية, الملاحظات: يستخدم إسمنت SRPC — ضروري في العراق والخليج بسبب ارتفاع نسبة الأملاح بالتربة, البيئة المناسبة: تربة مالحة / كبريتاتية',
                'created_at' => '2026-04-13 14:11:59',
                'updated_at' => '2026-04-13 14:16:34',
            ],
            [
                'id' => 8,
                'company_code' => 'general',
                'costPrice' => 0.00,
                'salePrice' => 0.00,
                'branch_id' => null,
                'classification' => 'C40',
                'cement' => 0.00,
                'sand' => 0.00,
                'gravel' => 0.00,
                'water' => 0.00,
                'cement_code' => null,
                'sand_code' => null,
                'gravel_code' => null,
                'water_code' => null,
                'notes' => 'النوع: ذاتي الرص (SCC), الاستخدام: مناطق كثيفة الحديد، أشكال معقدة، جدران رفيعة, الملاحظات: يتدفق دون هزاز — يقلل العمالة — حساس جداً للخلط — تكلفة أعلى, البيئة المناسبة: قوالب معقدة ومناطق مزدحمة بالحديد',
                'created_at' => '2026-04-13 14:11:59',
                'updated_at' => '2026-04-13 14:16:34',
            ],
            [
                'id' => 9,
                'company_code' => 'general',
                'costPrice' => 0.00,
                'salePrice' => 0.00,
                'branch_id' => null,
                'classification' => 'C35',
                'cement' => 0.00,
                'sand' => 0.00,
                'gravel' => 0.00,
                'water' => 0.00,
                'cement_code' => null,
                'sand_code' => null,
                'gravel_code' => null,
                'water_code' => null,
                'notes' => 'النوع: سريع الشك, الاستخدام: إصلاحات طارئة، طرق، جسور، جداول ضيقة, الملاحظات: يصل للمقاومة خلال 24-48 ساعة — يولّد حرارة عالية — خطر تشقق في الطقس الحار, البيئة المناسبة: مشاريع استعجالية — يُتجنب في الصيف',
                'created_at' => '2026-04-13 14:11:59',
                'updated_at' => '2026-04-13 14:16:34',
            ],
            [
                'id' => 10,
                'company_code' => 'general',
                'costPrice' => 0.00,
                'salePrice' => 0.00,
                'branch_id' => null,
                'classification' => 'C35',
                'cement' => 0.00,
                'sand' => 0.00,
                'gravel' => 0.00,
                'water' => 0.00,
                'cement_code' => null,
                'sand_code' => null,
                'gravel_code' => null,
                'water_code' => null,
                'notes' => 'النوع: كونكريت الطرق, الاستخدام: طرق، مدارج، أرضيات صناعية، مستودعات, الملاحظات: مقاوم للتآكل — يُضاف إليه ألياف — يحتاج فواصل تمدد واضحة وتمسيح دقيق, البيئة المناسبة: أسطح تحمل أحمالاً متكررة',
                'created_at' => '2026-04-13 14:11:59',
                'updated_at' => '2026-04-13 14:16:34',
            ],
            [
                'id' => 11,
                'company_code' => 'general',
                'costPrice' => 0.00,
                'salePrice' => 0.00,
                'branch_id' => null,
                'classification' => 'C35',
                'cement' => 0.00,
                'sand' => 0.00,
                'gravel' => 0.00,
                'water' => 0.00,
                'cement_code' => null,
                'sand_code' => null,
                'gravel_code' => null,
                'water_code' => null,
                'notes' => 'النوع: تحت الماء, الاستخدام: موانئ، دعامات جسور في الأنهار، أعمال بحرية, الملاحظات: يُضاف مادة Anti-Washout — يُصب بأنبوب Tremie — لا يُسمح بأي اهتزاز بعد الصب, البيئة المناسبة: بيئات مائية تحت الماء',
                'created_at' => '2026-04-13 14:11:59',
                'updated_at' => '2026-04-13 14:16:34',
            ],
            [
                'id' => 12,
                'company_code' => 'general',
                'costPrice' => 0.00,
                'salePrice' => 0.00,
                'branch_id' => null,
                'classification' => 'C15',
                'cement' => 0.00,
                'sand' => 0.00,
                'gravel' => 0.00,
                'water' => 0.00,
                'cement_code' => null,
                'sand_code' => null,
                'gravel_code' => null,
                'water_code' => null,
                'notes' => 'النوع: خفيف الوزن, الاستخدام: جدران غير إنشائية، أسقف مسطحة، عزل حراري, الملاحظات: ركام خفيف (Leca / Pumice) — كثافة أقل من 1800 kg/m3 — غير مناسب للعناصر الحاملة, البيئة المناسبة: عزل حراري وصوتي',
                'created_at' => '2026-04-13 14:11:59',
                'updated_at' => '2026-04-13 14:16:34',
            ],
            [
                'id' => 13,
                'company_code' => 'general',
                'costPrice' => 0.00,
                'salePrice' => 0.00,
                'branch_id' => null,
                'classification' => 'C30',
                'cement' => 0.00,
                'sand' => 0.00,
                'gravel' => 0.00,
                'water' => 0.00,
                'cement_code' => null,
                'sand_code' => null,
                'gravel_code' => null,
                'water_code' => null,
                'notes' => 'النوع: بيئي (Fly Ash), الاستخدام: بنية تحتية كبيرة، صبات ضخمة (Mass Concrete), الملاحظات: جزء من الإسمنت يُستبدل بمخلفات صناعية — يقلل حرارة الإماهة — أبطأ في المقاومة المبكرة, البيئة المناسبة: صبات حجمية كبيرة / مشاريع خضراء',
                'created_at' => '2026-04-13 14:11:59',
                'updated_at' => '2026-04-13 14:16:34',
            ],
            [
                'id' => 14,
                'company_code' => 'general',
                'costPrice' => 0.00,
                'salePrice' => 0.00,
                'branch_id' => null,
                'classification' => 'C80',
                'cement' => 0.00,
                'sand' => 0.00,
                'gravel' => 0.00,
                'water' => 0.00,
                'cement_code' => null,
                'sand_code' => null,
                'gravel_code' => null,
                'water_code' => null,
                'notes' => 'النوع: عالي الأداء (HPC), الاستخدام: جسور بحرية، منشآت نووية، أبراج فائقة الارتفاع, الملاحظات: متانة عالية جداً ونفاذية منخفضة — يتطلب إشرافاً دقيقاً في الخلط والصب والمعالجة, البيئة المناسبة: بيئات عدوانية وأحمال استثنائية',
                'created_at' => '2026-04-13 14:11:59',
                'updated_at' => '2026-04-13 14:16:34',
            ],
            [
                'id' => 15,
                'company_code' => 'general',
                'costPrice' => 0.00,
                'salePrice' => 0.00,
                'branch_id' => null,
                'classification' => 'C30',
                'cement' => 0.00,
                'sand' => 0.00,
                'gravel' => 0.00,
                'water' => 0.00,
                'cement_code' => null,
                'sand_code' => null,
                'gravel_code' => null,
                'water_code' => null,
                'notes' => 'النوع: ليفي (Fiber), الاستخدام: أرضيات صناعية، خزانات، أنفاق، جدران استنادية, الملاحظات: يُضاف ألياف فولاذية أو بولي بروبيلين — يقلل الشقوق ويرفع مقاومة الصدمات والشد, البيئة المناسبة: عناصر معرضة للشقوق والصدمات',
                'created_at' => '2026-04-13 14:11:59',
                'updated_at' => '2026-04-13 14:16:34',
            ],
        ];

        foreach ($rows as $row) {
            DB::table('concrete_mixes')->updateOrInsert(
                ['id' => $row['id']],
                $row
            );
        }
    }
}
